export const generalConfigurationConstants = {
    FETCH_REPO_DATA: "FETCH_REPO_DATA",
    FETCHED_REPO_DATA: "FETCHED_REPO_DATA",
    FILTER_REPO: "FILTER_REPO",
    FILTERED_REPO_DATA: "FILTERED_REPO_DATA",
    FILTER_REPO_BY_NAME: "FILTER_REPO_BY_NAME",
    FILTER_REPO_BY_LANGUAGE: "FILTER_REPO_BY_LANGUAGE",
    FILTER_REPO_BY_TYPE: "FILTER_REPO_BY_TYPE"
  };